---
apiVersion: v1
kind: Service
metadata:
  name: vault-svc
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
    - name: http
      port: 8200
      targetPort: http
  type: ClusterIP

