apiVersion: v1
kind: ConfigMap
metadata:
  name: datastaging-appsettings
data:
  appsettings.Production.json: |
    {
      "ConnectionStrings": {
        "MiddlewareContext": "Server=mssql;Database=HEAppE;User Id=sa;Password=HEAppE@123;",
        "Logging": "Server=mssql;Database=HEAppE;User Id=sa;Password=HEAppE@123;"
      },
      "ApplicationAPIConfiguration": {
        "AllowedHosts": ["*"],
        "AuthenticationParamHeaderName": "AuthKey",
        "AuthenticationToken": "dummy-token",
        "DeploymentConfiguration": {
          "Name": "openshift-instance",
          "Description": "Deployed to OpenShift",
          "Version": "v5.0.0",
          "DeployedIPAddress": "127.0.0.1"
        },
        "SwaggerConfiguration": {
          "Version": "v1.0.0",
          "Title": "Data-Staging API",
          "Description": "Data-Staging API",
          "Host": "http://datastaging-api-service:8080",
          "HostPostfix": "",
          "PrefixDocPath": "swagger",
          "TermOfUsageUrl": "https://example.com/terms",
          "License": "GPLv3",
          "LicenseUrl": "https://www.gnu.org/licenses/gpl-3.0.html",
          "ContactName": "Your Name",
          "ContactEmail": "support@example.com",
          "ContactUrl": "https://example.com"
        }
      }
    }
