apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-server-config
data:
  vault.hcl: |
    # Listener configuration
    listener "tcp" {
      address          = "0.0.0.0:8200"
      # cluster_address  = "0.0.0.0:8201" # Not needed for single node MVP
      tls_disable      = true # For MVP; enable TLS for production
    }

    # Storage backend
    storage "file" {
      path = "/vault/data" # This will be the PVC mount
    }

    # UI
    ui = true

    # Disable mlock for rootless, K8s environments
    disable_mlock = true

    # API settings
    api_addr = "http://0.0.0.0:8200" # Listen on all interfaces